import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";

// Redux
import { connect, useDispatch } from "react-redux";
import {
  AlbumsState,
  retrieveAlbums,
  // selectAlbum,
} from "../app/features/albums/albumsSlice";

import styles from "../styles/Home.module.css";

function Home({ data }) {
  // const album = useAppSelector(selectAlbum);
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(retrieveAlbums());
  }, [dispatch]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Photo Album</h1>
        <div>
          <ul>
            {data.albums.map((album) => (
              <li key={album.id}>
                <p>{album.title}</p>
              </li>
            ))}
          </ul>
        </div>
      </main>
    </div>
  );
}

const mapStateToProps = (state: AlbumsState) => ({
  data: state.albums,
});

export default connect(mapStateToProps)(Home);
